### ISSUE TITLE
Add WIKI page describing How-To configure Eclipse, and run "bndtools"-based Service Builder projects

### ISSUE THREAD

**Issue by FuadEfendi** [rotty3000/blade#137]
Should I run "gradle" to build it? 

I imported "blage.servicebuilder.web" project into Eclipse and I have errors with Eclipse classpath; should I ignore it?

I installed "bndtools" for Eclipse, just please I need starting point with this. 

Thank you!

**Comment by AndyWu2015** [comment]
Thanks again for trying blade !
The bndtool will automatically build and you can see a jar file in generated folder in project root .
You can paste your errors to here from eclipse error log view or maker view or problem view .
Thanks

**Comment by FuadEfendi** [comment]
The problem is that Eclipse won't even start build because we do not have this WIKI describing development environment setup. 
Questions like "how to configure bndtools" have no answer. "bndtools/cnf" uses plugin to point to Maven repository but existing versions of "bndtools" do not support that.

Eclipse error log? Ok, "cannot find portlet-api-2.0-sr12.jar".

Are we still using SR12?!!

**Comment by FuadEfendi** [comment]
Hi Andy,

Thanks for supporting "bndtools". Of course I can configure everything from scratch so that all will be built automatically without errors, I did that for few submodules already.

The question: does "BLADE/bndtools" support remote deployment to 11311 of Liferay Felix? How to configure that?

"cnf" contains some settings; I want to understand to configure it from scratch. I was unable to use provided "cnf", even using "cnf/.." as Eclipse workspace and importing it.

Thanks

**Comment by AndyWu2015** [comment]
Just see here: https://dev.liferay.com/web/liferay-7-community-expedition/feedback/-/message_boards/view_message/580604

**Comment by AndyWu2015** [comment]
close this
