### ISSUE TITLE
Change service builder consumer example to use declarative services?

### ISSUE THREAD

**Issue by deadcyclo** [rotty3000/blade#150]
Would it not be more "correct" to have the service builder web example consume the service in the same manner as in the example docs here: https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/publishing-liferay-services ?

**Comment by AndyWu2015** [comment]
Sure , but I think that FooLocalServiceUtil is using ServiceTracker which is an osgi util to get FooLocalService , it does not break the 6.2 developers in some way . If we use annotations to do this , that means developers should change their code more .

**Comment by rotty3000** [comment]
I have to agree with @deadcyclo on this one. We should not be using the `*Util` service wrappers anywhere in BLADE. BLADE is about designing software for Liferay without any technical dept. Since Service Builder publishes services, we should consume those services in the leanest way possible.

**Comment by AndyWu2015** [comment]
So *Util would be a deprecated manner to call methods and our recommended manner would be annotations ?

**Comment by rotty3000** [comment]
Rather than saying "using annotations" the idea is to "consume OSGi
services".

Declarative Services (DS) is just a very nice way to do this. Since the
portlet is already a component you are already using DS you should
reference the services in the same way.

:)

**Comment by AndyWu2015** [comment]
Sounds nice , I will work on it.

**Comment by AndyWu2015** [comment]
It did work , but here is a question : if  I want to call methods in FooLocalService in a jsp file , how can I get it ? Or I just still use *ServiceUtil to deal ?

**Comment by rotty3000** [comment]
Never use the *Utils at all.

Put the service as a bean in the request before including the JSP. That's
what you are supposed to do in JSPs.

**Comment by AndyWu2015** [comment]
got it.

**Comment by AndyWu2015** [comment]
done , see #160 , #161 and #162
