### ISSUE TITLE
Service builder examples are not working

### ISSUE THREAD

**Issue by deadcyclo** [rotty3000/blade#151]
They fail with a Caused by: org.hibernate.MappingException: entity class not found: blade.servicebuilder.model.impl.FooImpl on deploy

**Comment by gamerson** [comment]
Thanks Brendan, we will take a look.  What version of Portal were you
deploying to?

On Tue, Oct 27, 2015 at 10:30 PM, Brendan Johan Lee <
notifications@github.com> wrote:

> They fail with a Caused by: org.hibernate.MappingException: entity class
> not found: blade.servicebuilder.model.impl.FooImpl on deploy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/blade/issues/151>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by deadcyclo** [comment]
a1

**Comment by deadcyclo** [comment]
Also, note that I'm building with gradle

**Comment by AndyWu2015** [comment]
Sure ,I am going to work on it .

**Comment by AndyWu2015** [comment]
Hi Brendan , I am sorry to say that the service builder examples can't work in a1 version but I am happy to say it works well in latest build portal . I think we should follow the latest one and the servicebuilder is changing .

**Comment by deadcyclo** [comment]
Thanks Andy.

I sort of guessed that that might be the problem. I'll try downloading the latest nightly. I completely agree that the blade project needs to follow master.

**Comment by deadcyclo** [comment]
Hmmm... I'm still having the same issue on nightly from the 27th.

**Comment by deadcyclo** [comment]
Interestingly the maven project works. I'll try to compare the maven and gradle projects and see if I can fix it.

**Comment by deadcyclo** [comment]
Comparing the MANIFEST.MF of the two, the maven version (which works) has a huge Export-Package block that the gradle version doesn't

**Comment by deadcyclo** [comment]
Seems to be a missing Import-Package statement. I've submitted a pull request

**Comment by AndyWu2015** [comment]
Thanks Brendan , I did not notice that issue .

**Comment by deadcyclo** [comment]
Closing this :)
