### ISSUE TITLE
Something still seriously wrong with the service builder example

### ISSUE THREAD

**Issue by deadcyclo** [rotty3000/blade#164]
Hey @AndyWu2015 @gamerson and @rotty3000 !

Something is still seriously wrong with the service builder example. When building the service, no sql is generated so nothing is added to the database. The examples "work" since the old sql generated a month ago is still there, but make a minor change to the service and everything breaks. Try it by simply deleting the sql folder.

**Comment by gamerson** [comment]
Andy can you take a look ?  this could be because of service builder
changes we are trying to fix to get it to generate the sql folder.

On Tue, Nov 3, 2015 at 9:12 AM, Brendan Johan Lee <notifications@github.com>
wrote:

> Hey @AndyWu2015 <https://github.com/AndyWu2015> @gamerson
> <https://github.com/gamerson> and @rotty3000
> <https://github.com/rotty3000> !
>
> Something is still seriously wrong with the service builder example. When
> building the service, no sql is generated so nothing is added to the
> database. The examples "work" since the old sql generated a month ago is
> still there, but make a minor change to the service and everything breaks.
> Try it by simply deleting the sql folder.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/blade/issues/164>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by deadcyclo** [comment]
@gamerson @AndyWu2015 
I'm now pretty convinced that this is an issue with service builder, not with the blade project. Tried running the buildService task in bookmarks-service (randomly choosen ;) ) in liferay-portal on the master branch, and also there no SQL was generated.

**Comment by gamerson** [comment]
Yes ServiceBuilder does not create sql directories if they don't exist.  I
don't know if this is the way it has always been.  Andy is working on a
pull request to send to service builder that will always create the sql
folders if they don't exist.

On Tue, Nov 3, 2015 at 9:52 AM, Brendan Johan Lee <notifications@github.com>
wrote:

> @gamerson <https://github.com/gamerson> @AndyWu2015
> <https://github.com/AndyWu2015>
> I'm now pretty convinced that this is an issue with service builder, not
> with the blade project. Tried running the buildService task in
> bookmarks-service (randomly choosen ;) ) in liferay-portal on the master
> branch, and also there no SQL was generated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/blade/issues/164#issuecomment-153395914>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by AndyWu2015** [comment]
done , latest servicebuilder version 1.0.56 fixes this issue .
