### ISSUE TITLE
gradle service builder project broken again

### ISSUE THREAD

**Issue by deadcyclo** [rotty3000/blade#201]
:blade.servicebuilder.api:compileJava
Download https://repo1.maven.org/maven2/biz/aQute/bnd/biz.aQute.bnd.annotation/3.0.0/biz.aQute.bnd.annotation-3.0.0.pom
Download https://repo1.maven.org/maven2/biz/aQute/bnd/biz.aQute.bnd.annotation/3.0.0/biz.aQute.bnd.annotation-3.0.0.jar
:blade.servicebuilder.api:processResources UP-TO-DATE
:blade.servicebuilder.api:classes
:blade.servicebuilder.api:jar
:blade.servicebuilder.svc:compileJava
/tmp/blade/gradle/blade.servicebuilder.svc/src/main/java/blade/servicebuilder/service/persistence/impl/FooPersistenceImpl.java:46: error: cannot find symbol
import com.liferay.portal.service.persistence.CompanyProviderWrapper;
                                             ^
  symbol:   class CompanyProviderWrapper
  location: package com.liferay.portal.service.persistence
/tmp/blade/gradle/blade.servicebuilder.svc/src/main/java/blade/servicebuilder/service/persistence/impl/FooPersistenceImpl.java:2739: error: cannot find symbol
        @ServiceReference(type = CompanyProviderWrapper.class)
                                 ^
  symbol:   class CompanyProviderWrapper
  location: class FooPersistenceImpl
Note: /tmp/blade/gradle/blade.servicebuilder.svc/src/main/java/blade/servicebuilder/service/persistence/impl/FooPersistenceImpl.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:blade.servicebuilder.svc:compileJava FAILED

**Comment by AndyWu2015** [comment]
Thanks for reporting , I am gonna take a look at it.

**Comment by AndyWu2015** [comment]
Any errors until now ? @deadcyclo

**Comment by deadcyclo** [comment]
Hmm... Tried again. Completely fresh clone and completely removed all gradle caches. Still same error :(

**Comment by deadcyclo** [comment]
Had a look at the portal-service jar it's downloading, and CompanyProviderWrapper is missing from it.

https://repository.liferay.com/nexus/content/groups/liferay-ce/com/liferay/portal/portal-service/7.0.0-SNAPSHOT/portal-service-7.0.0-20151221.234545-2146.jar

**Comment by gamerson** [comment]
Perhaps we need to regenerate buildService?

On Wed, Jan 6, 2016 at 2:48 PM, Brendan Johan Lee <notifications@github.com>
wrote:

> Had a look at the portal-service jar it's downloading, and
> CompanyProviderWrapper is missing from it.
>
>
> https://repository.liferay.com/nexus/content/groups/liferay-ce/com/liferay/portal/portal-service/7.0.0-SNAPSHOT/portal-service-7.0.0-20151221.234545-2146.jar
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/blade/issues/201#issuecomment-169456752>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by AndyWu2015** [comment]
I believe that is because our portal-service.jar building is stopped again and the CompanyProviderWrapper was commited at 2015-12-22  but our latest jar's date is 2015-12-21 !
I succeeded because I built it locally.
Don't worry @gamerson @deadcyclo  , I will connect with Chas Austin the guy in charge of this .
Also I will update our service builder with the latest service builder plugin.

**Comment by FuadEfendi** [comment]
As of today, "CompanyProviderWrapper" is still not there (if you look in Eclipse dependencies, which load it from Nexus). Eclipse reports errors.

However, console builds Ok. Also, this "CompanyProviderWrapper" is used in annotations attributes only, I expect it should build Ok in this case; 

I suspect it is just compiler setting. Build is Ok but deployment could be problematic.

**Comment by AndyWu2015** [comment]
Hi guys , try it now , It should be ok now .
the latest jar is portal-service-7.0.0-20160109.232319-2159.jar

**Comment by deadcyclo** [comment]
@AndyWu2015 I can confirm it's working now. Closing this issue :)
