### ISSUE TITLE
Unresolved requirement: Import-Package: com.liferay.osgi.util; version="[2.0.0,3.0.0)"

### ISSUE THREAD

**Issue by FuadEfendi** [rotty3000/blade#208]
I am building Gradle ServiceBuilder API example, and deploying it, and I have this error:

    C:\java\git\tdf\tdf.api>blade deploy -p 12345 build\libs\tdf.api-1.0.0.jar
    Error
       0. [MBeanIntrospector.unwrapInvocationTargetException] java.io.IOException: Start of bundle with id 376 failed with message: Could not resolve module: tdf.api [376]
       Unresolved requirement: Import-Package: com.liferay.osgi.util; version="[2.0.0,3.0.0)"

I am using Liferay nightly build from January 05, 2016.

Felix console shows it "installed" (instead of "active").

**Comment by AndyWu2015** [comment]
Hi Fuad , can you send your code to my email or you can upload it to https://dev.liferay.com/web/liferay-7-community-expedition/feedback/-/message_boards/category/514265 so I can check it more , thanks !

**Comment by FuadEfendi** [comment]
Hi Andy, it is absolutely the same code as in "blade.servicebuilder.api"; the only difference: it is renamed & regenerated. Please try to regenerate & rebuild & deploy standard "blade.servicebuilder.api" (I'll do the same too)

**Comment by FuadEfendi** [comment]
HI Andy,

I tried to 'clean', 'buildService', 'build', and finally 'blade deploy' of the standard Gradle-based example of Service Builder, and I cannot deploy "api" module:
    $ blade deploy -p 12345 build/libs/blade.servicebuilder.api-1.0.0.jar
    Error
      0. [MBeanIntrospector.unwrapInvocationTargetException] java.io.IOException: Start of bundle with id 378 failed with message: Could not resolve module: blade.servicebuilder.api [378]
      Unresolved requirement: Import-Package: com.liferay.osgi.util; version="[2.0.0,3.0.0)"

I am using Liferay Nightly build from January 05 2016. I believe something wrong with Liferay: OSGi package "com.liferay.osgi.util" is not properly deployed. Thanks,

**Comment by rotty3000** [comment]
@FuadEfendi in your running portal can you login to the gogo shell `telnet localhost 11311` and run the command `packages com.liferay.osgi.util` and paste the full report here?

**Comment by FuadEfendi** [comment]
g! packages com.liferay.osgi.util
    No exported packages
    g!

**Comment by rotty3000** [comment]
it looks like you are missing the bundle 
https://repository.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.osgi.util/2.0.4/
can you install that one and see if it resolves the issue?

**Comment by FuadEfendi** [comment]
Thank you very much Raymond!

Installed; and "blade.servicebuilder.api" became instantly active (without reinstalling):

    378|Active     |    1|blade.servicebuilder.api (1.0.0.201601081639)
    379|Active     |    1|Liferay OSGi Utilities (2.0.4)
