### ISSUE TITLE
Unresolved requirement: Import-Package: com.liferay.util.portlet; version="[7.0.0,8.0.0)"

### ISSUE THREAD

**Issue by FuadEfendi** [rotty3000/blade#212]
Previously, I had to explicitly deploy OSGi-Util module to the newly installed Liferay; now I have similar problem.

I didn't try it yet with Liferay 7 B3. Only with nightly build version dated January 05, 2016.

I believe it has to be "exported" already; is it bug in Liferay?

**Comment by FuadEfendi** [comment]
g! packages com.liferay.util.portlet
No exported packages

**Comment by FuadEfendi** [comment]
UPDATE:
Tested with Liferay 7 B3. Same problem.

**Comment by FuadEfendi** [comment]
I fix it by explicitly installing this package; but it may or may not work, I don't know. It has to be 'exported' by Liferay.

**Comment by AndyWu2015** [comment]
I ran "packages com.liferay.util.portlet" and got nothing also.
Hi @FuadEfendi  , Import-Package: com.liferay.util.portlet; version="[7.0.0,8.0.0)" is written manully or generated by bnd ? 
By the way , can you share your code ? I don't know what the package is used for exactly.

**Comment by FuadEfendi** [comment]
Hi @AndyWu2015 
Public repo: https://github.com/Vertical-Search/tdf

Import was generated by BND tool

**Comment by AndyWu2015** [comment]
thanks for sharing , I will take time to take a look , may it help , if I have extra time . Sorry for some delay .

**Comment by rotty3000** [comment]
com.liferay.osgi.util now comes packaged with Liferay portal. It should be in the latest beta bundles and deployed by default because we use it all over the place.
