### ISSUE TITLE
Missing dependency when trying to add entry to the control panel

### ISSUE THREAD

**Issue by deadcyclo** [rotty3000/blade#213]
When trying to include com.liferay:com.liferay.application.list.api:1.0.0-SNAPSHOT in a standalone project (blade based) to be able to add an entry to the control panel, the following error occurs. The source for the missing package is in the liferay plugins master, but it seems that it hasn't been published to nexus for some reason.

Could not resolve all dependencies for configuration ':is.brendan.minecraftstuff.license.web:compile'.
> Could not find com.liferay:com.liferay.osgi.service.tracker.collections:1.0.1-SNAPSHOT.
  Searched in the following locations:
      https://repo1.maven.org/maven2/com/liferay/com.liferay.osgi.service.tracker.collections/1.0.1-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/com/liferay/com.liferay.osgi.service.tracker.collections/1.0.1-SNAPSHOT/com.liferay.osgi.service.tracker.collections-1.0.1-SNAPSHOT.pom
      https://repo1.maven.org/maven2/com/liferay/com.liferay.osgi.service.tracker.collections/1.0.1-SNAPSHOT/com.liferay.osgi.service.tracker.collections-1.0.1-SNAPSHOT.jar
      https://repository.liferay.com/nexus/content/groups/liferay-ce/com/liferay/com.liferay.osgi.service.tracker.collections/1.0.1-SNAPSHOT/maven-metadata.xml
      https://repository.liferay.com/nexus/content/groups/liferay-ce/com/liferay/com.liferay.osgi.service.tracker.collections/1.0.1-SNAPSHOT/com.liferay.osgi.service.tracker.collections-1.0.1-SNAPSHOT.pom
      https://repository.liferay.com/nexus/content/groups/liferay-ce/com/liferay/com.liferay.osgi.service.tracker.collections/1.0.1-SNAPSHOT/com.liferay.osgi.service.tracker.collections-1.0.1-SNAPSHOT.jar
  Required by:
      minecraftstuff-lr7:is.brendan.minecraftstuff.license.web:1.0.0 > com.liferay:com.liferay.application.list.api:1.0.0-SNAPSHOT

**Comment by rotty3000** [comment]
hey @deadcyclo can you try to refresh your dependency? It doesn't even look like  com.liferay.osgi.service.tracker.collections is a dependency of com.liferay.application.list.api:

https://repository.liferay.com/nexus/content/groups/liferay-ce/com/liferay/com.liferay.application.list.api/1.0.0-SNAPSHOT/com.liferay.application.list.api-1.0.0-20150820.224014-14.pom

**Comment by rotty3000** [comment]
oops my bad... wrong version.

**Comment by rotty3000** [comment]
I've asked for the dep to be published... note we're still working in the release process for all these modules. Sorry for the inconvenience!

**Comment by deadcyclo** [comment]
Now it seems the com.liferay.application.list.api itself is missing. (I opened a new ticket)

**Comment by rotty3000** [comment]
Same as for the other issue, I don't think this is an issue in BLADE and is upstream with liferay-portal.
