### ISSUE TITLE
Blade Service Builder compilation error

### ISSUE THREAD

**Issue by jrao** [rotty3000/blade#214]
Running gradle buildService followed by gradle build from the blade/gradle/blade.servicebuilder.svc folder produces the error below. Seems to be the result of a mismatch between the versions of the portal-service.jar and the com.liferay.portal.tools.service.builder.jar.

gradle build
:blade.servicebuilder.api:compileJava/home/$USER/blade/gradle/blade.servicebuilder.api/src/main/java/blade/servicebuilder/model/Foo.java:19: error: cannot find symbol
import com.liferay.portal.kernel.annotation.ImplementationClassName;
                                           ^
  symbol:   class ImplementationClassName
  location: package com.liferay.portal.kernel.annotation
/home/$USER/blade/gradle/blade.servicebuilder.api/src/main/java/blade/servicebuilder/model/Foo.java:32: error: cannot find symbol
@ImplementationClassName("blade.servicebuilder.model.impl.FooImpl")
 ^
  symbol: class ImplementationClassName
2 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':blade.servicebuilder.api:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.195 secs

**Comment by rotty3000** [comment]
Could not reproduce with all 4 tool chains today.
