### ISSUE TITLE
update samples to support all of the latest OSGi R6 features 

### ISSUE THREAD

**Issue by gamerson** [rotty3000/blade#218]
Maven
- org.apache.felix:maven-bundle-plugin:3.0.1
OR
- biz.aQute.bnd:bnd-maven-plugin:3.1.0

Gradle
- biz.aQute.bnd:biz.aQute.bnd.gradle:3.1.0
OR
- org.dm.gradle:gradle-bundle-plugin:0.8.1 (edited)

[12:32] 
all of those support all the OSGi R6 released features

**Comment by rotty3000** [comment]
Part of this is addressed in https://github.com/rotty3000/blade/pull/222

**Comment by rotty3000** [comment]
I think this is done as of the last cleanup commit https://github.com/rotty3000/blade/commit/b5c743a1f2232e06de316b32be5403ec36761703
