### ISSUE TITLE
Still missing artifacts in repository for building control panel apps

### ISSUE THREAD

**Issue by deadcyclo** [rotty3000/blade#219]
com.liferay:com.liferay.application.list.api:1.0.0-SNAPSHOT is missing from the repository, making it impossible to build control panel apps from blade. Seems like only the javadocs and tests have been published. https://repository.liferay.com/nexus/index.html#nexus-search;quick~application.list

**Comment by deadcyclo** [comment]
Cannot build the dependencies in master either: * What went wrong:
Could not resolve all dependencies for configuration ':apps:web-experience-management:application-list:application-list-api:compile'.
> Could not find com.liferay.portal:com.liferay.portal.impl:7.0.0-SNAPSHOT.

**Comment by rotty3000** [comment]
I think this is a bug at liferay-portal however and not with BLADE.

Can you file a ticket in Liferay's JIRA? Thx

**Comment by deadcyclo** [comment]
For future reference in case anybody else hits this page: https://issues.liferay.com/browse/LPS-63914

**Comment by gamerson** [comment]
Hey Brendan,

I will try to find out more from the releng team today why this isn't being
published

On Fri, Mar 4, 2016 at 3:46 AM, Brendan Johan Lee <notifications@github.com>
wrote:

> For future reference in case anybody else hits this page:
> https://issues.liferay.com/browse/LPS-63914
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/blade/issues/219#issuecomment-192210415>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by deadcyclo** [comment]
Awesome @gamerson . I've been trying to make a control panel app ever since I started playing with the blade project, and every single time something is wrong. The day I actually get it to work, I'm going to walk around with a huge grin on my face for days ;)

**Comment by gamerson** [comment]
Thank you for trying this, liferay extension points are just too many for
the guys on devtools team to test everything and Core guys are busy getting
ready for Liferay 7, so we can't do this well without guys like yourself on
community trying to get real stuff done.  please keep it up.

On Fri, Mar 4, 2016 at 9:35 AM, Brendan Johan Lee <notifications@github.com>
wrote:

> Awesome @gamerson <https://github.com/gamerson> . I've been trying to
> make a control panel app ever since I started playing with the blade
> project, and every single time something is wrong. The day I actually get
> it to work, I'm going to walk around with a huge grin on my face for days ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/blade/issues/219#issuecomment-192325701>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by deadcyclo** [comment]
I most definitely will. Watching LR-7 grow is a lot of fun, and it's really cool to see how much is being done "right" this time around. I've been drooling ever since I saw @rotty3000 talk about OSGI at devcon the first time years ago, and already things have gone way past my expectations. Now I just have to get around to trying the pure bnd-stuff you showed me last fall ;)
