### ISSUE TITLE
Issue with servicebuilder gradle project on Liferay Beta 8

### ISSUE THREAD

**Issue by jimanderton** [rotty3000/blade#230]
We're stuck on an issue getting OSGI services working under Beta 8. We've been trying various approaches and haven't been able to make any head way.

Basically, our services worked under Beta 6 but no longer function under Beta 8. They deploy successfully, but the api and service modules end up having no registered services and no services in use. We are having this same problem when we deploy the servicebuilder blade project as-is. We tried updating our bnd.bnd and build.gradle to match the latest commit here: https://github.com/rotty3000/blade/commit/5048ff511b6a2c51605398645d349b1603515135 but that didn't help.

There are many more details over on the LR7 forum here: https://dev.liferay.com/web/liferay-7-community-expedition/feedback/-/message_boards/message/735916

Any idea what's going on?

Thanks!

**Comment by rotty3000** [comment]
Take note that the Liferay manifest headers all start now with `Liferay-`,
so the services won't start if you have the "provisional" header names.

So check that first.

**Comment by jimanderton** [comment]
Hi Ray,

Thank you for your response. I'm trying to understand what would have changed from Beta 6 to Beta 8 that would be preventing the services from running. Are there 'Liferay-' headers that are required now that were not required in beta 6?

Maybe a simpler question that gets to this issue would be: Should the gradle/blade.servicebuilder.api, svc, and web projects build and deploy successfully as-is? If not, what changes to the headers would we need to make?

Thanks again

**Comment by rbohl** [comment]
@jimanderton 

I was having a similar problem to the one you describe, and I solved it by updating the bnd.bnd of my service module (I have a multi-module Service Builder Application based on the BLADE template). I had to make these changes:

Spring-Context became Liferay-Spring-Context

Require-SchemaVersion became Liferay-SchemaVersion


Here's a more complete example of the headers that changed, I think:

```Liferay-Require-SchemaVersion: 1.0.0
Liferay-Service: true
Liferay-Spring-Context: META-INF/spring
Require-Capability:\
    liferay.extender;\
    filter:="(&(liferay.extender=spring.extender)(version>=1.0)(!(version>=2.0)))"
```

**Comment by jimanderton** [comment]
@rbohl 

This is very helpful. Thanks!

It looks like changing "Spring-Context" to "Liferay-Spring-Context" and "Require-SchemaVersion" to "Liferay-Require-SchemaVersion" got the service module deployed properly. It was very nice to finally see "Running abc SQL scripts" in the log. 

Now, I'm working with the API module since it is still not showing any registered services.  I'll keep digging, but just wondered if you recall also having to make any similar changes to get your API module working?

**Comment by rotty3000** [comment]
But why would the API bundle have services? At least in the default SB
build, there are no services in the API. The services are from the svc
bundle. The API just holds the .... API.

**Comment by jimanderton** [comment]
What I'm specifically looking for is some indication that the API is using the service.  For example, if I use "blade sh b" to look at the polls api module, I can see under "Services in Use" that it is using com.liferay.polls.service.PollsQuestionLocalService.

However, when I use "b" to look at my API module, I see "No services in use"  And, when I try to call the API, I'm seeing a java.lang.NullPointerException being thrown on the line in the ***LocalServiceUtil method that looks like this:

return getService().countByWorkspaceId(workspaceId);

I'm assuming this is because the API isn't accessing the service

**Comment by deadcyclo** [comment]
What I find interesting is that my own services worked fine as soon as I updated them according to the latest changes, but the blade example doesn't seem to work. The web-part of the servicebuilder example also seems to have an issue, it doesn't show up as a portlet anywhere in the GUI. I'm going to try to get time to investigate further today.

**Comment by deadcyclo** [comment]
One step closer here. After clearing caches, I suddenly had problems with my own modules. Got them working again by adding -includeresource: src/main/resources to the bnd.bnd file in my svc-project. Tried the same in the blade.servicebuilder.svc project, but still having issues with it.

Something funky is going on here.

**Comment by deadcyclo** [comment]
I'm having issues with several of the other blade modules on b8 as well. I'm going to test against master now.

**Comment by deadcyclo** [comment]
Unfortunately master seems to be quite broken at the moment

**Comment by jimanderton** [comment]
I wanted to confirm that I am able to successfully deploy and use the blade.servicebuilder.api/svc/web projects on beta 8. The only change that needs to be made is the following two lines in the svc project's bnd.bnd file:
```
-Require-SchemaVersion: 1.0.0
-Spring-Context: META-INF/spring

+Liferay-Require-SchemaVersion: 1.0.0
+Liferay-Spring-Context: META-INF/spring
```
I wanted to say THANKS to everyone that contributed clues here. Looking forward to changes settling down when LR7 gets to RC. :-)

I'm still working to determine why calls to my api module are failing but it's useful to know that the example project here does work with this change.

I'll leave the scope of this github issue as needing to update the bnd.bnd files to reflect the new header values. I'll report further progress related to the API issue over on the [Liferay 7 Forum](https://dev.liferay.com/web/liferay-7-community-expedition/feedback/-/message_boards/message/735916)

**Comment by deadcyclo** [comment]
@jimanderton well spotted. I was going to submit a pull request, but things move quickly and the build is failing again today with a new error. I'm submitting a new ticket and investigating.

**Comment by gamerson** [comment]
thanks everyone, I'll get this fixed, I've been working on samples a lot today and I wont sleep  until it works :)

**Comment by deadcyclo** [comment]
Just a heads up here. I couldn't get this working on b8, but everything works fine on master.
