### ISSUE TITLE
Blade servicebuilder failing.

### ISSUE THREAD

**Issue by deadcyclo** [rotty3000/blade#234]
Today, the service builder started producing illegal code again. I'm guessing the service builder itself needs an update? (and yes, I cleared my gradle cache)

/home/brendan/work/liferay/test7/blade/gradle/blade.servicebuilder.svc/src/main/java/blade/servicebuilder/service/base/FooLocalServiceBaseImpl.java:693: error: method getSqlUpdate in class SqlUpdateFactoryUtil cannot be applied to given types;
                        SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                                                                  ^
  required: DataSource,String,int[]
  found: DataSource,String
  reason: actual and formal argument lists differ in length
/home/brendan/work/liferay/test7/blade/gradle/blade.servicebuilder.svc/src/main/java/blade/servicebuilder/service/base/FooServiceBaseImpl.java:417: error: method getSqlUpdate in class SqlUpdateFactoryUtil cannot be applied to given types;
                        SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                                                                  ^
  required: DataSource,String,int[]
  found: DataSource,String
  reason: actual and formal argument lists differ in length
Note: /home/brendan/work/liferay/test7/blade/gradle/blade.servicebuilder.svc/src/main/java/blade/servicebuilder/service/persistence/impl/FooPersistenceImpl.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:blade.servicebuilder.svc:compileJava FAILED

**Comment by deadcyclo** [comment]
Actually, most likely the other way around? portal-service needs to be updated in the repository?

**Comment by gamerson** [comment]
Hey @deadcyclo this should be fixed in my most recent commits.  Please reopen if it is isn't fixed.  Specifically this one:

https://github.com/rotty3000/blade/pull/242

**Comment by deadcyclo** [comment]
Confirmed working on todays master.
