### ISSUE TITLE
trouble with the jsp-portlet as well

### ISSUE THREAD

**Issue by deadcyclo** [rotty3000/blade#250]
Seems the jsp portlet is having issues as well. (On current master). It shows up in the list of portlets without a title, and it isn't including Language.properties.

**Comment by csierra** [comment]
hey, 

this is a duplicate of #247

**Comment by csierra** [comment]
we have a fix on its way

**Comment by deadcyclo** [comment]
sigh. that's what I get for not paying attention ;)

**Comment by csierra** [comment]
haha :joy:
