### ISSUE TITLE
Blade project broken

### ISSUE THREAD

**Issue by deadcyclo** [rotty3000/blade#252]
Hey guys!

On todays master, seems like the blade project is severly broken, and needs updating. Things build ok, but don't run properly, and I'm seeing errors like:

Unresolved requirement: Import-Package: com.liferay.portal.kernel.configuration; version="[7.0.0,8.0.0)"

Unresolved requirement: Import-Package: com.liferay.portal.kernel.io.unsync; version="[7.0.0,8.0.0)"

Unresolved requirement: Import-Package: com.liferay.portal.kernel.annotation; version="[7.0.0,8.0.0)"

**Comment by deadcyclo** [comment]
Fixed in pull requst  #253

**Comment by gamerson** [comment]
#253 is merged now
