### ISSUE TITLE
IP-com.liferay.portal.kernel.struts.StrutsAction

### ISSUE THREAD

**Issue by kameshsampath** [rotty3000/blade#29]
Add BLADE samples for Integration Point - `com.liferay.portal.kernel.struts.StrutsAction`

**Comment by kameshsampath** [comment]
The gradle and maven samples for integration point StrutsAction pushed to repo

**Comment by gamerson** [comment]
can you link the merge commit id here?

On Mon, Jun 8, 2015 at 4:28 PM, Kamesh Sampath <notifications@github.com>
wrote:

> The gradle and maven samples for integration point StrutsAction pushed to
> repo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/blade/issues/29#issuecomment-109906439>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by kameshsampath** [comment]
commit f6a328e9a199c00446d350328f9f8fc5230ab86d
